### ISSUE TITLE
ModuleNotFoundError: No module named 'generateQRcode'

### ISSUE THREAD

**Issue by int75** [marco0antonio0/py-connector-whatsapp-unofficial#2]
python main.py

Results in
Traceback (most recent call last):
  File "/Users/oct/dev/py-connector-whatsapp-unofficial/main.py", line 1, in <module>
    from services import automation
  File "/Users/oct/dev/py-connector-whatsapp-unofficial/services/__init__.py", line 1, in <module>
    from .bot import automation
  File "/Users/oct/dev/py-connector-whatsapp-unofficial/services/bot.py", line 5, in <module>
    from generateQRcode import createQRCODE
ModuleNotFoundError: No module named 'generateQRcode'

**Comment by catd724** [comment]
i am facing the same issue here

**Comment by marco0antonio0** [comment]
The issue with "No module named 'generateQRcode'" has been successfully resolved by changing the import to services.generateQRcode. Your @catd724  fix has been merged into the codebase.

**Comment by marco0antonio0** [comment]
🚀 A new version of the WhatsApp connector has been released, which includes your correction along with updates to the internal structure, refactored method calls, and overall improvements to automation flow.

📄 For full details, please refer to the updated README.md. @int75 @catd724

**Comment by marco0antonio0** [comment]
Issue resolved.
